import csv
import json
import os
import shutil

demo_products = [
    # Electronics Sample Products
    {
        "sku": "DEMO-ELEC-001",
        "name": "AuraSound Studio Wireless ANC Headphones",
        "brand": "AuraSound",
        "category": "Electronics",
        "price": 219.99,
        "currency": "USD",
        "features": "40mm Beryllium Drivers, 45-Hour Battery Life, Active Hybrid ANC, Bluetooth 5.3",
        "specifications": json.dumps({"Driver": "40mm Beryllium", "Weight": "240g", "Charging": "USB-C Fast Charge"}),
        "target_audience": "Audiophiles, remote workers, and commuters",
        "primary_keywords": "wireless anc headphones, studio bluetooth headphones",
        "secondary_keywords": "noise cancelling headset, long battery headphones",
        "usp": "Studio-grade acoustics with hybrid active noise cancellation",
        "material": "Magnesium Alloy & Memory Foam",
        "dimensions": "7.5 x 6.2 x 3.1 in",
        "color": "Midnight Black",
        "weight": "240g",
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-002",
        "name": "PulseTrack Pro Fitness Smartwatch V5",
        "brand": "PulseTrack",
        "category": "Electronics",
        "price": 169.50,
        "currency": "USD",
        "features": "Continuous SpO2 & ECG Monitor, 50m Waterproof, Built-in GPS, 8-Day Battery",
        "specifications": json.dumps({"Display": "1.4-inch AMOLED", "Waterproof": "50 meters"}),
        "target_audience": "Athletes, runners, and fitness enthusiasts",
        "primary_keywords": "smart fitness watch, health tracker watch",
        "secondary_keywords": "waterproof smartwatch, gps activity tracker",
        "usp": "Medical-grade biometric accuracy in an ultra-light watch",
        "material": "Aerospace Aluminum & Silicone",
        "dimensions": "1.6 x 1.4 x 0.4 in",
        "color": "Ocean Blue",
        "weight": "42g",
        "image_url": "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-003",
        "name": "NovaBook Ultra 14 OLED Laptop",
        "brand": "NovaBook",
        "category": "Electronics",
        "price": 1199.00,
        "currency": "USD",
        "features": "Intel Core i7 13th Gen, 16GB RAM, 1TB NVMe SSD, 2.8K 120Hz OLED Screen",
        "specifications": json.dumps({"Processor": "Intel i7-13700H", "RAM": "16GB LPDDR5", "Storage": "1TB SSD"}),
        "target_audience": "Executives, software engineers, and digital creators",
        "primary_keywords": "ultra thin laptop, oled touchscreen notebook",
        "secondary_keywords": "intel i7 laptop, lightweight business ultrabook",
        "usp": "Vivid 2.8K 120Hz OLED clarity inside a 1.1kg magnesium chassis",
        "material": "Magnesium Aluminum Alloy",
        "dimensions": "12.3 x 8.7 x 0.55 in",
        "color": "Starlight Silver",
        "weight": "1.1kg",
        "image_url": "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-004",
        "name": "ApexShot 4K Vlog Mirrorless Camera",
        "brand": "ApexShot",
        "category": "Electronics",
        "price": 849.00,
        "currency": "USD",
        "features": "4K 60fps Uncropped Video, AI Real-Time Eye Tracking, Flip Touchscreen",
        "specifications": json.dumps({"Sensor": "24.2MP APS-C", "ISO": "100-32000"}),
        "target_audience": "Content creators, YouTubers, and travel vloggers",
        "primary_keywords": "4k vlogging camera, mirrorless video camera",
        "secondary_keywords": "youtube camera, autofocus vlog camera",
        "usp": "Cinematic 4K 60fps video with instant AI eye tracking autofocus",
        "material": "Polycarbonate Body",
        "dimensions": "4.7 x 2.6 x 2.3 in",
        "color": "Graphite Grey",
        "weight": "388g",
        "image_url": "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-005",
        "name": "VisionPro 34-Inch Ultrawide Curved Gaming Monitor",
        "brand": "VisionPro",
        "category": "Electronics",
        "price": 529.99,
        "currency": "USD",
        "features": "UWQHD 3440x1440, 165Hz Refresh Rate, 1ms Response Time, HDR400",
        "specifications": json.dumps({"Resolution": "3440 x 1440", "Curvature": "1500R"}),
        "target_audience": "Gamers, video editors, and multitaskers",
        "primary_keywords": "34 inch curved monitor, ultrawide gaming monitor",
        "secondary_keywords": "165hz uwqhd screen, curved monitor for work",
        "usp": "1500R panoramic curved immersive view for lag-free gaming",
        "material": "Aluminum Stand & Matte Frame",
        "dimensions": "31.8 x 18.2 x 9.4 in",
        "color": "Matte Black",
        "weight": "7.8kg",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-006",
        "name": "VoltMax 100W Fast Charging Laptop Power Bank",
        "brand": "VoltMax",
        "category": "Electronics",
        "price": 89.99,
        "currency": "USD",
        "features": "25000mAh Capacity, 100W USB-C Power Delivery, TSA Flight Approved",
        "specifications": json.dumps({"Capacity": "25000mAh / 92.5Wh", "Output": "100W Max"}),
        "target_audience": "Digital nomads, business travelers, and students",
        "primary_keywords": ["laptop power bank", "100w fast charging battery"],
        "secondary_keywords": ["high capacity portable charger", "usb c powerbank"],
        "usp": "Powers MacBooks and laptops at full 100W speed anywhere",
        "material": "Anodized Fireproof Aluminum",
        "dimensions": "6.2 x 3.1 x 1.0 in",
        "color": "Space Grey",
        "weight": "490g",
        "image_url": "https://images.unsplash.com/photo-1609592424074-8848b813f8aa?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-007",
        "name": "ClearTone TWS Noise Isolating Earbuds",
        "brand": "ClearTone",
        "category": "Electronics",
        "price": 64.99,
        "currency": "USD",
        "features": ["Environmental Mic Noise Cancellation", "IPX5 Waterproof", "Wireless Charging Case"],
        "specifications": json.dumps({"Bluetooth": "5.3", "Playtime": "30 Hours Total"}),
        "target_audience": "Commuters, runners, and casual music lovers",
        "primary_keywords": "true wireless earbuds, bluetooth earphones with mic",
        "secondary_keywords": "sweatproof wireless buds, affordable TWS earbuds",
        "usp": "Crisp voice calls with zero pressure ergonomic ear tip seal",
        "material": "Polycarbonate",
        "dimensions": "2.2 x 1.8 x 0.9 in",
        "color": "Pearl White",
        "weight": "45g",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-008",
        "name": "TactilePro RGB Hot-Swap Mechanical Keyboard",
        "brand": "TactilePro",
        "category": "Electronics",
        "price": 109.99,
        "currency": "USD",
        "features": ["Hot-Swappable Switches, Per-Key RGB, PBT Keycaps, Detachable Type-C"],
        "specifications": json.dumps({"Layout": "75%", "Switches": "Gateron Yellow Linear"}),
        "target_audience": "Gamers, programmers, and office typists",
        "primary_keywords": "rgb mechanical keyboard, hot swappable gaming keyboard",
        "secondary_keywords": "75 percent keyboard, pbt keycaps mechanical keyboard",
        "usp": "Creamy acoustics with pre-lubed linear switches",
        "material": "PBT Keycaps & Aluminum Plate",
        "dimensions": "12.8 x 5.5 x 1.4 in",
        "color": "Teal & Chalk White",
        "weight": "950g",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-009",
        "name": "SkyHawk 4K GPS Mini Drone 249g",
        "brand": "SkyHawk",
        "category": "Electronics", "price": 419.00,
        "currency": "USD",
        "features": "Under 249g Weight, 4K 30fps 3-Axis Gimbal, 32-Min Flight, 10km Range",
        "specifications": json.dumps({"Weight": "242g", "Camera": "4K HDR 3-Axis"}),
        "target_audience": "Travel videographers, beginners, and aerial photographers",
        "primary_keywords": "4k mini drone under 249g, gps camera drone",
        "secondary_keywords": "3 axis gimbal drone, portable folding drone",
        "usp": "Ultra-light folding drone for smooth 4K videos without FAA registration",
        "material": "Lightweight Composite",
        "dimensions": "5.5 x 3.2 x 2.2 in",
        "color": "Arctic White",
        "weight": "242g",
        "image_url": "https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-ELEC-010",
        "name": "NetSpeed WiFi 7 Mesh Router System",
        "brand": "NetSpeed",
        "category": "Electronics",
        "price": 349.00,
        "currency": "USD",
        "features": "WiFi 7 Tri-Band MLO, 11 Gbps Speed, 6,000 Sq Ft Coverage, 10G Port",
        "specifications": json.dumps({"Bands": "2.4GHz / 5GHz / 6GHz", "Ports": "10GbE"}),
        "target_audience": "Smart homes, 4K/8K streamers, and online gaming households",
        "primary_keywords": "wifi 7 mesh router, tri band home mesh system",
        "secondary_keywords": "gigabit wireless router, high speed home network",
        "usp": "Zero-lag WiFi 7 multi-link speeds across whole home",
        "material": "Polycarbonate",
        "dimensions": "6.8 x 4.2 x 4.2 in",
        "color": "Satin White",
        "weight": "820g",
        "image_url": "https://images.unsplash.com/photo-1544197150-b99a580bb7a8?auto=format&fit=crop&w=600&q=80"
    },

    # Fashion Sample Products
    {
        "sku": "DEMO-FASH-011",
        "name": "UrbanShield All-Weather Waterproof Rain Jacket",
        "brand": "UrbanShield",
        "category": "Fashion",
        "price": 129.99,
        "currency": "USD",
        "features": "3-Layer Breathable Membrane, 15,000mm Waterproof, Seam-Sealed Zippers",
        "specifications": json.dumps({"Waterproof Rating": "15,000mm", "Material": "100% Recycled Polyester"}),
        "target_audience": "Urban commuters, hikers, and outdoor adventurers",
        "primary_keywords": "waterproof rain jacket, breathable outdoor jacket",
        "secondary_keywords": "windbreaker jacket, all weather coat",
        "usp": "Complete storm protection paired with sleek urban tailoring",
        "material": "100% Recycled Ripstop Polyester",
        "dimensions": "Men S-XXL",
        "color": "Charcoal Black",
        "weight": "450g",
        "image_url": "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-012",
        "name": "CloudStride Nitrogen-Cushioned Running Shoes",
        "brand": "CloudStride",
        "category": "Fashion",
        "price": 115.00,
        "currency": "USD",
        "features": "Nitrogen-Infused Foam Midsole, Flyknit Breathable Mesh Upper, High Grip Outsole",
        "specifications": json.dumps({"Heel Drop": "8mm", "Weight": "230g"}),
        "target_audience": "Marathon runners, daily joggers, and gym goers",
        "primary_keywords": "lightweight running shoes, cushioned sneakers",
        "secondary_keywords": "breathable athletic shoes, road running footwear",
        "usp": "Cloud-like responsive cushioning engineered for high mileage",
        "material": "Flyknit Mesh & Rubber",
        "dimensions": "US Mens 7-13",
        "color": "Electric Crimson",
        "weight": "230g",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-013",
        "name": "HeritageFlex 4-Way Stretch Slim Jeans",
        "brand": "HeritageFlex",
        "category": "Fashion",
        "price": 79.50,
        "currency": "USD",
        "features": "4-Way Comfort Stretch Denim, 5-Pocket Styling, Reinforced Stress Seams",
        "specifications": json.dumps({"Composition": "98% Organic Cotton, 2% Elastane", "Fit": "Slim Tapered"}),
        "target_audience": "Modern men seeking stylish all-day denim comfort",
        "primary_keywords": "slim fit stretch jeans, men tapered denim",
        "secondary_keywords": "comfortable blue jeans, 5 pocket flexible denim",
        "usp": "Authentic denim look with 4-way stretch unrestricted freedom",
        "material": "98% Organic Cotton, 2% Elastane",
        "dimensions": "Waist 28-40 in",
        "color": "Vintage Indigo Wash",
        "weight": "580g",
        "image_url": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-014",
        "name": "CozyHaven 350 GSM Organic Fleece Hoodie",
        "brand": "CozyHaven",
        "category": "Fashion",
        "price": 62.00,
        "currency": "USD",
        "features": "350 GSM Heavyweight Organic French Terry, Double-Lined Hood, Kangaroo Pocket",
        "specifications": json.dumps({"Fabric Weight": "350 GSM", "Material": "100% Organic Cotton"}),
        "target_audience": "Loungewear lovers, students, and streetwear fans",
        "primary_keywords": "organic cotton hoodie, heavyweight fleece sweatshirt",
        "secondary_keywords": "cozy pullover hoodie, relaxed fit sweater",
        "usp": "Ultra-soft 350 GSM organic French terry fleece built for lasting cozy warmth",
        "material": "100% Organic Cotton",
        "dimensions": "Unisex XS-XXL",
        "color": "Oatmeal Heather",
        "weight": "620g",
        "image_url": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-015",
        "name": "SolStyle Polarized Aviator Sunglasses UV400",
        "brand": "SolStyle",
        "category": "Fashion",
        "price": 45.00,
        "currency": "USD",
        "features": "UV400 100% Protection, TAC Polarized Lenses, Monel Metal Frame, Spring Hinges",
        "specifications": json.dumps({"Lens Width": "58mm", "Bridge": "14mm"}),
        "target_audience": "Drivers, beachgoers, and stylish outdoorsmen",
        "primary_keywords": "polarized aviator sunglasses, uv400 metal frame shades",
        "secondary_keywords": "driving sunglasses, classic unisex eyewear",
        "usp": "Glare-free optical precision wrapped in a timeless metal frame",
        "material": "Monel Metal & TAC Lens",
        "dimensions": "Standard Adult",
        "color": "Gold Frame / Dark Green Lens",
        "weight": "28g",
        "image_url": "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-016",
        "name": "LuxeLeather Italian Grain Leather Tote Handbag",
        "brand": "LuxeLeather",
        "category": "Fashion",
        "price": 189.00,
        "currency": "USD",
        "features": "Full-Grain Italian Cowhide Leather, Padded 15-Inch Laptop Pocket, Gold Brass Hardware",
        "specifications": json.dumps({"Capacity": "16 Liters", "Fit": "15\" Laptop"}),
        "target_audience": "Working executives, professionals, and stylish commuters",
        "primary_keywords": "leather laptop tote bag, women work handbag",
        "secondary_keywords": "minimalist tote, genuine leather shoulder bag",
        "usp": "Full-grain supple leather structured to carry laptops effortlessly",
        "material": "Full-Grain Cowhide Leather",
        "dimensions": "15.5 x 12.0 x 5.5 in",
        "color": "Cognac Tan",
        "weight": "850g",
        "image_url": "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-017",
        "name": "ThermaWool Merino Hiking Crew Socks (3-Pack)",
        "brand": "ThermaWool",
        "category": "Fashion",
        "price": 29.99,
        "currency": "USD",
        "features": "70% Merino Wool, Heel & Toe Cushioning, Arch Compression, Anti-Blister Seams",
        "specifications": json.dumps({"Content": "70% Merino Wool, 25% Nylon, 5% Elastane", "Pack": "3 Pairs"}),
        "target_audience": "Hikers, campers, and outdoor workers",
        "primary_keywords": "merino wool hiking socks, cushioned crew socks",
        "secondary_keywords": "anti blister socks, warm moisture wicking socks",
        "usp": "Blister-free thermal regulation that keeps feet dry all day",
        "material": "Merino Wool Blend",
        "dimensions": "Shoe Sizes 6-12",
        "color": "Olive / Charcoal / Navy",
        "weight": "180g",
        "image_url": "https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-018",
        "name": "VogueParis Double-Breasted Cotton Trench Coat",
        "brand": "VogueParis",
        "category": "Fashion",
        "price": 229.00,
        "currency": "USD",
        "features": "Water-Resistant Cotton Twill, Removable Waist Belt, Classic Epaulettes",
        "specifications": json.dumps({"Material": "100% Cotton Twill", "Lining": "Viscose Satin"}),
        "target_audience": "Fashion-conscious women, commuters, and travelers",
        "primary_keywords": "double breasted trench coat, women waterproof trench",
        "secondary_keywords": "classic beige trench coat, elegant belted spring coat",
        "usp": "Timeless Parisian silhouette tailored in water-repellent gabardine twill",
        "material": "100% Cotton Twill",
        "dimensions": "Sizes XS-XL",
        "color": "Honey Beige",
        "weight": "920g",
        "image_url": "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-019",
        "name": "MilanoCraft Goodyear Welted Leather Penny Loafers",
        "brand": "MilanoCraft",
        "category": "Fashion",
        "price": 165.00,
        "currency": "USD",
        "features": ["Hand-Burnished Calfskin Leather, Goodyear Welted Sole, Memory Insole"],
        "specifications": json.dumps({"Construction": "Goodyear Welted", "Material": "Italian Calfskin"}),
        "target_audience": "Business professionals and smart-casual dressers",
        "primary_keywords": "men leather penny loafers, handcrafted dress loafers",
        "secondary_keywords": "goodyear welted slip on shoes, calfskin leather footwear",
        "usp": "Hand-stitched Goodyear welted calfskin that offers custom ergonomic comfort",
        "material": "Calfskin Leather",
        "dimensions": "US Mens 7-13",
        "color": "Burnished Dark Walnut",
        "weight": "440g",
        "image_url": "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=600&q=80"
    },
    {
        "sku": "DEMO-FASH-020",
        "name": "PureLinen 100% French Linen Resort Shirt",
        "brand": "PureLinen",
        "category": "Fashion",
        "price": 68.00,
        "currency": "USD",
        "features": "100% French Flax Linen, Pre-Washed Vintage Softness, Mother of Pearl Buttons",
        "specifications": json.dumps({"Material": "100% French Linen", "Fit": "Resort Casual"}),
        "target_audience": "Vacationers, summer dressers, and beachgoers",
        "primary_keywords": "linen button down shirt, men French linen resort shirt",
        "secondary_keywords": "breathable summer shirt, organic linen long sleeve",
        "usp": "Ultra-breathable French flax pre-washed for instant breezy comfort",
        "material": "100% French Linen",
        "dimensions": "Men S-XXL",
        "color": "Sky Blue",
        "weight": "210g",
        "image_url": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=600&q=80"
    }
]

# Write demo_batch_upload_products.csv
csv_path = os.path.join("data", "demo_batch_upload_products.csv")
headers = [
    "sku", "name", "brand", "category", "price", "currency",
    "features", "specifications", "target_audience",
    "primary_keywords", "secondary_keywords", "usp",
    "material", "dimensions", "color", "weight", "image_url"
]

with open(csv_path, "w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(headers)
    for p in demo_products:
        writer.writerow([
            p.get("sku", ""),
            p.get("name", ""),
            p.get("brand", ""),
            p.get("category", ""),
            p.get("price", ""),
            p.get("currency", "USD"),
            p.get("features", ""),
            p.get("specifications", ""),
            p.get("target_audience", ""),
            p.get("primary_keywords", ""),
            p.get("secondary_keywords", ""),
            p.get("usp", ""),
            p.get("material", ""),
            p.get("dimensions", ""),
            p.get("color", ""),
            p.get("weight", ""),
            p.get("image_url", "")
        ])

print(f"Saved {len(demo_products)} demo products to {csv_path}")

# Write demo_batch_upload_products.json
json_path = os.path.join("data", "demo_batch_upload_products.json")
with open(json_path, "w", encoding="utf-8") as f:
    json.dump(demo_products, f, indent=2)

# Copy to artifacts directory for direct chat download
artifact_dir = r"C:\Users\sujay\.gemini\antigravity\brain\c57e001a-2bad-4153-b729-2bf8581028ed"
if os.path.exists(artifact_dir):
    shutil.copy(csv_path, os.path.join(artifact_dir, "demo_batch_upload_products.csv"))
    shutil.copy(json_path, os.path.join(artifact_dir, "demo_batch_upload_products.json"))
    print(f"Successfully copied demo files to artifact directory: {artifact_dir}")
